### PR TITLE
Add additional events, and correct CurrentUser.nsfw_allowed

### PR DESCRIPTION
**Pull request by tonyarnold**
These changes fix SwiftcordApp/Swiftcord#53.

### CODE REVIEW

**Comment by cryptoAlgorithm** [comment]
Hi! The unhandled ready supplemental and session replace events shouldn't prevent the connection from completing, but failing to decode the CurrentUser certainly would. Could you see if there are any decoding errors for the READY event in the logs?

**Comment by tonyarnold** [comment]
You're absolutely right — just fixing the optional property of `CurrentUser` was enough to get this to work.

**Comment by cryptoAlgorithm** [comment]
Yup, I was worried that the CurrentUser had more optional properties than I knew of, thats why I needed testers <3

**Comment by cryptoAlgorithm** [comment]
@tonyarnold are you in the Swiftcord Discord server? I'll give you the contributor role if you are ;D

**Comment by tonyarnold** [comment]
I've just joined now 🎉

**Pull request merged**
